[package]
name = "abc375"
version = "0.1.0"
edition = "2021"

[dependencies] 
once_cell = "1.20.2"
proconio = { version = "0.5.0", features = ["derive"] }
rstest = "0.23.0"

[[bin]]
name = "abc375-a"
path = "src/bin/a.rs"

